export const content = [
  "Milk",
  "Egg",
  "Butter",
  "Cream",
  "Buttermilk",
  "Cheese Slices",
  "Gelatin",
  "Sour Cream",
  "Bacon",
  "Scrambled Egg",
  "Yoghurt",
  "Mayonnaise",
  "Chicken Stock",
  "Beef Stock",
  "Condensed Milk",
  "Worcestershire Sauce",
  "Parmesan",
  "Cream Cheese",
  "Milk Chocolate",
  "Honey",
  "Sugar",
  "Pulled Pork",
  "Pulled Chicken",
  "Salmon",
  "Ground Beef"
];

// export const content = [
//   { name: "Milk", alt: ["SOY MILK", "ALMOND MILK", "OAT MILK"] },
//   { name: "Egg", alt: "CHIA EGG" },
//   { name: "Butter", alt: "MARGERINE" },
//   { name: "Cream", alt: "COCONUT CREAM" },
//   { name: "BUTTERMILK", alt: "" },
//   { name: "CHEESE SLICES", alt: "" },
//   { name: "GELATIN", alt: "" },
//   { name: "SOUR CREAM", alt: "" },
//   { name: "BACON", alt: "" },
//   { name: "YOGHURT", alt: "" },
//   { name: "CHICKEN STOCK", alt: "" },
//   { name: "BEEF STOCK", alt: "" },
//   { name: "MAYONNAISE", alt: "" },
//   { name: "SCRAMBLED EGG", alt: "" },
//   { name: "CONDENSED MILK", alt: "" }
// ];
